name: "Test AMBuild Action"
on: push

jobs:
  test_action_1:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, windows-latest, macos-latest]
        python-version: [2.7, 3.8]
        arch: [x64]
        include:
          - os: windows-latest
            python-version: 2.7
            arch: x86
          - os: windows-latest
            python-version: 3.8
            arch: x86
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          arch: ${{ matrix.arch }}
      - name: Update pip and setuptools
        run: |
          python -m pip install --upgrade pip setuptools
          pip install wheel
        shell: bash
      - name: Build test#1
        uses: WildCard65/invoke-ambuild@master
        with:
          project-root: test#1
      - name: Run output
        run: build/test1
        shell: bash
  test_action_2:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, windows-latest, macos-latest]
        python-version: [2.7, 3.8]
        arch: [x64]
        include:
          - os: windows-latest
            python-version: 2.7
            arch: x86
          - os: windows-latest
            python-version: 3.8
            arch: x86
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          arch: ${{ matrix.arch }}
      - name: Update pip and setuptools
        run: |
          python -m pip install --upgrade pip setuptools
          pip install wheel
        shell: bash
      - name: Build test#2
        uses: WildCard65/invoke-ambuild@master
        with:
          project-root: test#2
          build-folder: binout
          configure-args: --lobster "Jeremy"
      - name: Run output
        run: binout/test2
        shell: bash
  test_action_3:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, windows-latest, macos-latest]
        python-version: [2.7, 3.8]
        arch: [x64]
        include:
          - os: windows-latest
            python-version: 2.7
            arch: x86
          - os: windows-latest
            python-version: 3.8
            arch: x86
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          arch: ${{ matrix.arch }}
      - name: Update pip and setuptools
        run: |
          python -m pip install --upgrade pip setuptools
          pip install wheel
        shell: bash
      - name: Build test#2
        uses: WildCard65/invoke-ambuild@master
        with:
          project-root: test#1
          build-folder: binout
          delete-build: true
